// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LevelUpAPI.Models;

public partial class LevelUpDBContext : DbContext
{
    public LevelUpDBContext(DbContextOptions<LevelUpDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Graduate> Graduates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Graduate>(entity =>
        {
            entity.HasKey(e => e.GraduateId).HasName("PK__Graduate__F27C3DADC8B36C53");

            entity.ToTable("Graduate");

            entity.Property(e => e.GraduateId)
                .ValueGeneratedNever()
                .HasColumnName("graduateID");
            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.DateCreated).HasColumnName("dateCreated");
            entity.Property(e => e.DateEdited).HasColumnName("dateEdited");
            entity.Property(e => e.DateOfBirth).HasColumnName("dateOfBirth");
            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("emailAddress");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("firstName");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("lastName");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("userName");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}